### ISSUE TITLE
How about training time?

### ISSUE THREAD

**Issue by Ha0Tang** [ennauata/housegan#10]
Hi, I would like to know how many `n_epochs` you used to get the results in your paper? and how long does it take to complete training on two GPUs? Thanks.

As far as I know, you set `n_epochs=1000000`, while for me, I can train only about 70 epochs on two RTX 6000 GPUs (each one has 24G) for one day, thus it needs about 1000000/70=14285 days to finish the training. That's really unacceptable.

**Comment by ennauata** [comment]
The number of epochs currently set in the code is not expected to be reached, in the experiments I usually leave it training for 300k iterations, which should take ~2 days of training on a single GPU.

**Comment by Ha0Tang** [comment]
Do you use`batch_size=32`?

**Comment by Ha0Tang** [comment]
What type of GPU do you use, and what is the GPU memory？

**Comment by ennauata** [comment]
Yes, batch_size=32.

I was training on 2 Titan RTX 24GB each, but I also tried on a single GTX 1080 11GB and worked fine.

**Comment by Ha0Tang** [comment]
It’s weird, our GPUs are similar, but it looks like it takes a quite long time for me to finish training.

**Comment by ennauata** [comment]
I wonder how long it takes to run 10k iterations (not epochs) in your case. We are considering one epoch to be one loop over the entire training set and one iteration to be one pass for one mini batch.

**Comment by Ha0Tang** [comment]
I see, it means you set `n_epochs` around 100 since each epoch consists of around 3k iterations. Am I correct?

In this case, I can finish the training in about one day.

**Comment by ennauata** [comment]
That's correct.

**Comment by Ha0Tang** [comment]
That makes sense now, thank you so much.
