### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Ha0Tang** [ennauata/housegan#9]
When I tried to train the model, I encountered the following error:

> 107315
> target samples: defaultdict(<class 'int'>, {3: 4126, 7: 18971, 13: 5454, 9: 16395, 6: 16179, 17: 241, 1: 2138, 8: 17591, 4: 7005, 5: 11547, 2: 2667, 14: 2875, 18: 122, 15: 1248, 16: 531, 20: 47, 24: 19, 19: 82, 23: 13, 22: 25, 21: 20, 34: 1, 32: 2, 26: 4, 25: 5, 30: 1, 29: 1, 31: 1, 27: 2, 35: 1, 28: 1})
> 5000
> target samples: defaultdict(<class 'int'>, {11: 1787, 12: 1260, 10: 1953})
> Traceback (most recent call last):
>   File "main.py", line 198, in <module>
>     gen_mks = data_parallel(generator, (z, given_nds, given_eds), indices)
>   File "main.py", line 103, in data_parallel
>     output_device = device_ids[0]
> IndexError: list index out of range

Any ideas?

**Comment by ennauata** [comment]
Are you using GPUs for training? Maybe try setting multi_gpu to False in main.py.

**Comment by Ha0Tang** [comment]
Yes, I have 8 GPUs on my machine.

**Comment by ennauata** [comment]
I see, I would recommend setting multi_gpu to False for a potential quick fix. But if you want to train on all your GPUs, I would start by checking the variable device_ids. I believe, If all the GPUs are visible then device_ids should not be out of range.

**Comment by Ha0Tang** [comment]
everything is ok when set `multi_gpu=False`

**Comment by Ha0Tang** [comment]
`device_ids` returns `[]`, that's weird!

**Comment by ennauata** [comment]
That's strange, either the gpus are not visible for some reason or it could be caused by some change in Pytorch version.
